pub const FTErrrEnum = enum(c_int) {
    FT_Err_Ok = 0,
    FT_Err_Cannot_Open_Resource = 1,
    FT_Err_Unknown_File_Format = 2,
    FT_Err_Invalid_File_Format = 3,
    FT_Err_Invalid_Version = 4,
    FT_Err_Lower_Module_Version = 5,
    FT_Err_Invalid_Argument = 6,
    FT_Err_Unimplemented_Feature = 7,
    FT_Err_Invalid_Table = 8,
    FT_Err_Invalid_Offset = 9,
    FT_Err_Array_Too_Large = 10,
    FT_Err_Missing_Module = 11,
    FT_Err_Missing_Property = 12,
    FT_Err_Invalid_Glyph_Index = 16,
    FT_Err_Invalid_Character_Code = 17,
    FT_Err_Invalid_Glyph_Format = 18,
    FT_Err_Cannot_Render_Glyph = 19,
    FT_Err_Invalid_Outline = 20,
    FT_Err_Invalid_Composite = 21,
    FT_Err_Too_Many_Hints = 22,
    FT_Err_Invalid_Pixel_Size = 23,
    FT_Err_Invalid_SVG_Document = 24,
    FT_Err_Invalid_Handle = 32,
    FT_Err_Invalid_Library_Handle = 33,
    FT_Err_Invalid_Driver_Handle = 34,
    FT_Err_Invalid_Face_Handle = 35,
    FT_Err_Invalid_Size_Handle = 36,
    FT_Err_Invalid_Slot_Handle = 37,
    FT_Err_Invalid_CharMap_Handle = 38,
    FT_Err_Invalid_Cache_Handle = 39,
    FT_Err_Invalid_Stream_Handle = 40,
    FT_Err_Too_Many_Drivers = 48,
    FT_Err_Too_Many_Extensions = 49,
    FT_Err_Out_Of_Memory = 64,
    FT_Err_Unlisted_Object = 65,
    FT_Err_Cannot_Open_Stream = 81,
    FT_Err_Invalid_Stream_Seek = 82,
    FT_Err_Invalid_Stream_Skip = 83,
    FT_Err_Invalid_Stream_Read = 84,
    FT_Err_Invalid_Stream_Operation = 85,
    FT_Err_Invalid_Frame_Operation = 86,
    FT_Err_Nested_Frame_Access = 87,
    FT_Err_Invalid_Frame_Read = 88,
    FT_Err_Raster_Uninitialized = 96,
    FT_Err_Raster_Corrupted = 97,
    FT_Err_Raster_Overflow = 98,
    FT_Err_Raster_Negative_Height = 99,
    FT_Err_Too_Many_Caches = 112,
    FT_Err_Invalid_Opcode = 128,
    FT_Err_Too_Few_Arguments = 129,
    FT_Err_Stack_Overflow = 130,
    FT_Err_Code_Overflow = 131,
    FT_Err_Bad_Argument = 132,
    FT_Err_Divide_By_Zero = 133,
    FT_Err_Invalid_Reference = 134,
    FT_Err_Debug_OpCode = 135,
    FT_Err_ENDF_In_Exec_Stream = 136,
    FT_Err_Nested_DEFS = 137,
    FT_Err_Invalid_CodeRange = 138,
    FT_Err_Execution_Too_Long = 139,
    FT_Err_Too_Many_Function_Defs = 140,
    FT_Err_Too_Many_Instruction_Defs = 141,
    FT_Err_Table_Missing = 142,
    FT_Err_Horiz_Header_Missing = 143,
    FT_Err_Locations_Missing = 144,
    FT_Err_Name_Table_Missing = 145,
    FT_Err_CMap_Table_Missing = 146,
    FT_Err_Hmtx_Table_Missing = 147,
    FT_Err_Post_Table_Missing = 148,
    FT_Err_Invalid_Horiz_Metrics = 149,
    FT_Err_Invalid_CharMap_Format = 150,
    FT_Err_Invalid_PPem = 151,
    FT_Err_Invalid_Vert_Metrics = 152,
    FT_Err_Could_Not_Find_Context = 153,
    FT_Err_Invalid_Post_Table_Format = 154,
    FT_Err_Invalid_Post_Table = 155,
    FT_Err_DEF_In_Glyf_Bytecode = 156,
    FT_Err_Missing_Bitmap = 157,
    FT_Err_Missing_SVG_Hooks = 158,
    FT_Err_Syntax_Error = 160,
    FT_Err_Stack_Underflow = 161,
    FT_Err_Ignore = 162,
    FT_Err_No_Unicode_Glyph_Name = 163,
    FT_Err_Glyph_Too_Big = 164,
    FT_Err_Missing_Startfont_Field = 176,
    FT_Err_Missing_Font_Field = 177,
    FT_Err_Missing_Size_Field = 178,
    FT_Err_Missing_Fontboundingbox_Field = 179,
    FT_Err_Missing_Chars_Field = 180,
    FT_Err_Missing_Startchar_Field = 181,
    FT_Err_Missing_Encoding_Field = 182,
    FT_Err_Missing_Bbx_Field = 183,
    FT_Err_Bbx_Too_Big = 184,
    FT_Err_Corrupted_Font_Header = 185,
    FT_Err_Corrupted_Font_Glyphs = 186,
    FT_Err_Max = 187,
    _,
};

pub const FreeTypeError = error{
    // Ok,
    Cannot_Open_Resource,
    Unknown_File_Format,
    Invalid_File_Format,
    Invalid_Version,
    Lower_Module_Version,
    Invalid_Argument,
    Unimplemented_Feature,
    Invalid_Table,
    Invalid_Offset,
    Array_Too_Large,
    Missing_Module,
    Missing_Property,
    Invalid_Glyph_Index,
    Invalid_Character_Code,
    Invalid_Glyph_Format,
    Cannot_Render_Glyph,
    Invalid_Outline,
    Invalid_Composite,
    Too_Many_Hints,
    Invalid_Pixel_Size,
    Invalid_SVG_Document,
    Invalid_Handle,
    Invalid_Library_Handle,
    Invalid_Driver_Handle,
    Invalid_Face_Handle,
    Invalid_Size_Handle,
    Invalid_Slot_Handle,
    Invalid_CharMap_Handle,
    Invalid_Cache_Handle,
    Invalid_Stream_Handle,
    Too_Many_Drivers,
    Too_Many_Extensions,
    Out_Of_Memory,
    Unlisted_Object,
    Cannot_Open_Stream,
    Invalid_Stream_Seek,
    Invalid_Stream_Skip,
    Invalid_Stream_Read,
    Invalid_Stream_Operation,
    Invalid_Frame_Operation,
    Nested_Frame_Access,
    Invalid_Frame_Read,
    Raster_Uninitialized,
    Raster_Corrupted,
    Raster_Overflow,
    Raster_Negative_Height,
    Too_Many_Caches,
    Invalid_Opcode,
    Too_Few_Arguments,
    Stack_Overflow,
    Code_Overflow,
    Bad_Argument,
    Divide_By_Zero,
    Invalid_Reference,
    Debug_OpCode,
    ENDF_In_Exec_Stream,
    Nested_DEFS,
    Invalid_CodeRange,
    Execution_Too_Long,
    Too_Many_Function_Defs,
    Too_Many_Instruction_Defs,
    Table_Missing,
    Horiz_Header_Missing,
    Locations_Missing,
    Name_Table_Missing,
    CMap_Table_Missing,
    Hmtx_Table_Missing,
    Post_Table_Missing,
    Invalid_Horiz_Metrics,
    Invalid_CharMap_Format,
    Invalid_PPem,
    Invalid_Vert_Metrics,
    Could_Not_Find_Context,
    Invalid_Post_Table_Format,
    Invalid_Post_Table,
    DEF_In_Glyf_Bytecode,
    Missing_Bitmap,
    Missing_SVG_Hooks,
    Syntax_Error,
    Stack_Underflow,
    Ignore,
    No_Unicode_Glyph_Name,
    Glyph_Too_Big,
    Missing_Startfont_Field,
    Missing_Font_Field,
    Missing_Size_Field,
    Missing_Fontboundingbox_Field,
    Missing_Chars_Field,
    Missing_Startchar_Field,
    Missing_Encoding_Field,
    Missing_Bbx_Field,
    Bbx_Too_Big,
    Corrupted_Font_Header,
    Corrupted_Font_Glyphs,
    Max,
    Unexpected,
};

pub fn ftErrorFromInt(err: c_int) FreeTypeError!void {
    return switch (@as(FTErrrEnum, @enumFromInt(err))) {
        .FT_Err_Ok => {},
        .FT_Err_Cannot_Open_Resource => FreeTypeError.Cannot_Open_Resource,
        .FT_Err_Unknown_File_Format => FreeTypeError.Unknown_File_Format,
        .FT_Err_Invalid_File_Format => FreeTypeError.Invalid_File_Format,
        .FT_Err_Invalid_Version => FreeTypeError.Invalid_Version,
        .FT_Err_Lower_Module_Version => FreeTypeError.Lower_Module_Version,
        .FT_Err_Invalid_Argument => FreeTypeError.Invalid_Argument,
        .FT_Err_Unimplemented_Feature => FreeTypeError.Unimplemented_Feature,
        .FT_Err_Invalid_Table => FreeTypeError.Invalid_Table,
        .FT_Err_Invalid_Offset => FreeTypeError.Invalid_Offset,
        .FT_Err_Array_Too_Large => FreeTypeError.Array_Too_Large,
        .FT_Err_Missing_Module => FreeTypeError.Missing_Module,
        .FT_Err_Missing_Property => FreeTypeError.Missing_Property,
        .FT_Err_Invalid_Glyph_Index => FreeTypeError.Invalid_Glyph_Index,
        .FT_Err_Invalid_Character_Code => FreeTypeError.Invalid_Character_Code,
        .FT_Err_Invalid_Glyph_Format => FreeTypeError.Invalid_Glyph_Format,
        .FT_Err_Cannot_Render_Glyph => FreeTypeError.Cannot_Render_Glyph,
        .FT_Err_Invalid_Outline => FreeTypeError.Invalid_Outline,
        .FT_Err_Invalid_Composite => FreeTypeError.Invalid_Composite,
        .FT_Err_Too_Many_Hints => FreeTypeError.Too_Many_Hints,
        .FT_Err_Invalid_Pixel_Size => FreeTypeError.Invalid_Pixel_Size,
        .FT_Err_Invalid_SVG_Document => FreeTypeError.Invalid_SVG_Document,
        .FT_Err_Invalid_Handle => FreeTypeError.Invalid_Handle,
        .FT_Err_Invalid_Library_Handle => FreeTypeError.Invalid_Library_Handle,
        .FT_Err_Invalid_Driver_Handle => FreeTypeError.Invalid_Driver_Handle,
        .FT_Err_Invalid_Face_Handle => FreeTypeError.Invalid_Face_Handle,
        .FT_Err_Invalid_Size_Handle => FreeTypeError.Invalid_Size_Handle,
        .FT_Err_Invalid_Slot_Handle => FreeTypeError.Invalid_Slot_Handle,
        .FT_Err_Invalid_CharMap_Handle => FreeTypeError.Invalid_CharMap_Handle,
        .FT_Err_Invalid_Cache_Handle => FreeTypeError.Invalid_Cache_Handle,
        .FT_Err_Invalid_Stream_Handle => FreeTypeError.Invalid_Stream_Handle,
        .FT_Err_Too_Many_Drivers => FreeTypeError.Too_Many_Drivers,
        .FT_Err_Too_Many_Extensions => FreeTypeError.Too_Many_Extensions,
        .FT_Err_Out_Of_Memory => FreeTypeError.Out_Of_Memory,
        .FT_Err_Unlisted_Object => FreeTypeError.Unlisted_Object,
        .FT_Err_Cannot_Open_Stream => FreeTypeError.Cannot_Open_Stream,
        .FT_Err_Invalid_Stream_Seek => FreeTypeError.Invalid_Stream_Seek,
        .FT_Err_Invalid_Stream_Skip => FreeTypeError.Invalid_Stream_Skip,
        .FT_Err_Invalid_Stream_Read => FreeTypeError.Invalid_Stream_Read,
        .FT_Err_Invalid_Stream_Operation => FreeTypeError.Invalid_Stream_Operation,
        .FT_Err_Invalid_Frame_Operation => FreeTypeError.Invalid_Frame_Operation,
        .FT_Err_Nested_Frame_Access => FreeTypeError.Nested_Frame_Access,
        .FT_Err_Invalid_Frame_Read => FreeTypeError.Invalid_Frame_Read,
        .FT_Err_Raster_Uninitialized => FreeTypeError.Raster_Uninitialized,
        .FT_Err_Raster_Corrupted => FreeTypeError.Raster_Corrupted,
        .FT_Err_Raster_Overflow => FreeTypeError.Raster_Overflow,
        .FT_Err_Raster_Negative_Height => FreeTypeError.Raster_Negative_Height,
        .FT_Err_Too_Many_Caches => FreeTypeError.Too_Many_Caches,
        .FT_Err_Invalid_Opcode => FreeTypeError.Invalid_Opcode,
        .FT_Err_Too_Few_Arguments => FreeTypeError.Too_Few_Arguments,
        .FT_Err_Stack_Overflow => FreeTypeError.Stack_Overflow,
        .FT_Err_Code_Overflow => FreeTypeError.Code_Overflow,
        .FT_Err_Bad_Argument => FreeTypeError.Bad_Argument,
        .FT_Err_Divide_By_Zero => FreeTypeError.Divide_By_Zero,
        .FT_Err_Invalid_Reference => FreeTypeError.Invalid_Reference,
        .FT_Err_Debug_OpCode => FreeTypeError.Debug_OpCode,
        .FT_Err_ENDF_In_Exec_Stream => FreeTypeError.ENDF_In_Exec_Stream,
        .FT_Err_Nested_DEFS => FreeTypeError.Nested_DEFS,
        .FT_Err_Invalid_CodeRange => FreeTypeError.Invalid_CodeRange,
        .FT_Err_Execution_Too_Long => FreeTypeError.Execution_Too_Long,
        .FT_Err_Too_Many_Function_Defs => FreeTypeError.Too_Many_Function_Defs,
        .FT_Err_Too_Many_Instruction_Defs => FreeTypeError.Too_Many_Instruction_Defs,
        .FT_Err_Table_Missing => FreeTypeError.Table_Missing,
        .FT_Err_Horiz_Header_Missing => FreeTypeError.Horiz_Header_Missing,
        .FT_Err_Locations_Missing => FreeTypeError.Locations_Missing,
        .FT_Err_Name_Table_Missing => FreeTypeError.Name_Table_Missing,
        .FT_Err_CMap_Table_Missing => FreeTypeError.CMap_Table_Missing,
        .FT_Err_Hmtx_Table_Missing => FreeTypeError.Hmtx_Table_Missing,
        .FT_Err_Post_Table_Missing => FreeTypeError.Post_Table_Missing,
        .FT_Err_Invalid_Horiz_Metrics => FreeTypeError.Invalid_Horiz_Metrics,
        .FT_Err_Invalid_CharMap_Format => FreeTypeError.Invalid_CharMap_Format,
        .FT_Err_Invalid_PPem => FreeTypeError.Invalid_PPem,
        .FT_Err_Invalid_Vert_Metrics => FreeTypeError.Invalid_Vert_Metrics,
        .FT_Err_Could_Not_Find_Context => FreeTypeError.Could_Not_Find_Context,
        .FT_Err_Invalid_Post_Table_Format => FreeTypeError.Invalid_Post_Table_Format,
        .FT_Err_Invalid_Post_Table => FreeTypeError.Invalid_Post_Table,
        .FT_Err_DEF_In_Glyf_Bytecode => FreeTypeError.DEF_In_Glyf_Bytecode,
        .FT_Err_Missing_Bitmap => FreeTypeError.Missing_Bitmap,
        .FT_Err_Missing_SVG_Hooks => FreeTypeError.Missing_SVG_Hooks,
        .FT_Err_Syntax_Error => FreeTypeError.Syntax_Error,
        .FT_Err_Stack_Underflow => FreeTypeError.Stack_Underflow,
        .FT_Err_Ignore => FreeTypeError.Ignore,
        .FT_Err_No_Unicode_Glyph_Name => FreeTypeError.No_Unicode_Glyph_Name,
        .FT_Err_Glyph_Too_Big => FreeTypeError.Glyph_Too_Big,
        .FT_Err_Missing_Startfont_Field => FreeTypeError.Missing_Startfont_Field,
        .FT_Err_Missing_Font_Field => FreeTypeError.Missing_Font_Field,
        .FT_Err_Missing_Size_Field => FreeTypeError.Missing_Size_Field,
        .FT_Err_Missing_Fontboundingbox_Field => FreeTypeError.Missing_Fontboundingbox_Field,
        .FT_Err_Missing_Chars_Field => FreeTypeError.Missing_Chars_Field,
        .FT_Err_Missing_Startchar_Field => FreeTypeError.Missing_Startchar_Field,
        .FT_Err_Missing_Encoding_Field => FreeTypeError.Missing_Encoding_Field,
        .FT_Err_Missing_Bbx_Field => FreeTypeError.Missing_Bbx_Field,
        .FT_Err_Bbx_Too_Big => FreeTypeError.Bbx_Too_Big,
        .FT_Err_Corrupted_Font_Header => FreeTypeError.Corrupted_Font_Header,
        .FT_Err_Corrupted_Font_Glyphs => FreeTypeError.Corrupted_Font_Glyphs,
        .FT_Err_Max => FreeTypeError.Max,
        _ => FreeTypeError.Unexpected,
    };
}
